// <auto-generated />
using System;
using CursoAspNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CursoAspNet.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190416000610_Primeiro Migration")]
    partial class PrimeiroMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursoAspNet.Domain.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Citm");

                    b.Property<string>("Ditm");

                    b.Property<string>("Poor");

                    b.Property<double>("Qtdp");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CursoAspNet.Domain.Operations.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dope");

                    b.Property<string>("Nope");

                    b.Property<int>("Nseq");

                    b.Property<int?>("OrderId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("CursoAspNet.Domain.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Dorg");

                    b.Property<DateTime>("Dtrc");

                    b.Property<int?>("ItemId");

                    b.Property<string>("Nuor");

                    b.Property<double>("Qtnc");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CursoAspNet.Domain.Operations.Operation", b =>
                {
                    b.HasOne("CursoAspNet.Domain.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("CursoAspNet.Domain.Orders.Order", b =>
                {
                    b.HasOne("CursoAspNet.Domain.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
